language: scala
sudo: false
dist: trusty
matrix:
  include:
  - env: SBT_VERSION="0.13.18"
    jdk: openjdk7
  - env: SBT_VERSION="1.0.4"
    jdk: oraclejdk8
  - env: SBT_VERSION="1.1.0"
    jdk: oraclejdk8
  - env: SBT_VERSION="1.2.6"
    jdk: openjdk11
    dist: xenial
script:
- sbt "^^ ${SBT_VERSION}" test scripted
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
before_cache:
- rm -rf $HOME/.ivy2/cache/com.github.gseitz
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
