language: scala
sudo: false
dist: xenial
matrix:
  include:
  - env: SBT_VERSION="0.13.18"
    jdk: openjdk8
  - env: SBT_VERSION="1.2.8"
    jdk: openjdk8
  - env: SBT_VERSION="1.3.0-RC3"
    jdk: openjdk8
  - env: SBT_VERSION="1.2.8"
    jdk: openjdk11
script:
- sbt "^^ ${SBT_VERSION}" test scripted
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
before_cache:
- rm -rf $HOME/.ivy2/cache/com.github.gseitz
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
