language: scala
sudo: false
dist: xenial
matrix:
  include:
  - env: SBT_VERSION="0.13.18"
    jdk: openjdk8
  - env: SBT_VERSION="1.2.8"
    jdk: openjdk8
  - env: SBT_VERSION="1.3.0-RC3"
    jdk: openjdk8
  - env: SBT_VERSION="1.2.8"
    jdk: openjdk11
  - os: windows
    language: bash
    env:
    - JDK="adopt@1.8.212-04"
    before_install:
    - wget "https://raw.githubusercontent.com/DanySK/Gravis-CI/c8f400623d8f756ef7c/.install-jdk-travis.sh"
    - source .install-jdk-travis.sh
    script:
    - wget https://raw.githubusercontent.com/paulp/sbt-extras/3c8fcadc3376e/sbt && chmod +x ./sbt
    - ./sbt "^^ 1.2.8" test scripted
script:
- sbt "^^ ${SBT_VERSION}" test scripted
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
before_cache:
- rm -rf $HOME/.ivy2/cache/com.github.gseitz
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
